FROM node:25-alpine AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG NODE_ENV

ENV NODE_ENV=$NODE_ENV

RUN npm run build

RUN npm test

FROM node:25-alpine

WORKDIR /app
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 1337
CMD ["node", "dist/index.js"]
